[package]
name = "cool-file-host"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.5", features = ["multipart"] }
tokio = { version = "1.39.3", features = ["full"] }
serde = { version = "1.0.208", features = ["derive"]}
chrono = "0.4.38"
sanitize-filename = "0.5.0"